#!/usr/bin/env python3
"""Turn assets/art.py into src/gfx.s and src/gfx.h.

Tiles   : 32 bytes each, 16 lines of (left byte, right byte).
Sprites : 64 bytes each, 32 bytes of bitmap then 32 bytes of mask, where a
          mask bit of 1 keeps the screen. The mask is the sprite dilated by
          one pixel and inverted, so a sprite always stands in a one-pixel
          halo of paper and never merges with the floor pattern.
Font    : 64 glyphs x 8 bytes, ASCII 32..95.
"""
import os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, os.path.join(ROOT, "assets"))
import art  # noqa: E402

TILES = ["WALL", "FLOOR", "FLOOR2", "DOOR", "DOOR_OPEN", "STAIRS", "PILLAR",
         "WALL_F", "FLOOR_F", "DOOR_F"]
SPRITES = ["WARRIOR", "COMMANDO", "GOBLIN", "RAT", "SKELETON", "SPIDER", "JELLY",
           "WIZARD", "BEHOLDER", "ORBDROID", "SCRAPDRONE", "TURRET",
           "CHEST", "GOLD", "KEY", "BOOK", "ORB", "DICE", "TORCH"]


def dither(tone, x, y, isolated):
    if tone == 0:
        return 0
    if tone == 3 or isolated:
        return 1
    if tone == 2:
        return 1 if (x + y) % 2 == 0 else 0
    return 1 if (x % 2 == 0 and y % 2 == 0) else 0


def remap(rows, tones):
    return [[tones.get(t, t) for t in r] for r in rows] if tones else rows


# What a tile looks like once it is only REMEMBERED. Everything drops a tone
# and the isolated-pixel rule is off, so a wall goes from solid to a checker
# and a floor keeps a quarter of its specks. Dropping BRIGHT alone left the
# whole explored map as solid blocks of dark yellow, which is the map shouting
# at you about rooms you already know.
DIM = {0: 0, 1: 1, 2: 1, 3: 2}


def bitmap(rows, tones=None, keep_isolated=True):
    rows = remap(rows, tones)
    h, w = len(rows), len(rows[0])
    out = []
    for y in range(h):
        line = []
        for x in range(w):
            t = rows[y][x]
            iso = keep_isolated and t and all(
                rows[y + dy][x + dx] == 0
                for dy, dx in ((-1, 0), (1, 0), (0, -1), (0, 1))
                if 0 <= y + dy < h and 0 <= x + dx < w)
            line.append(dither(t, x, y, iso))
        out.append(line)
    return out


def dim_bitmap(rows, tones=None):
    return bitmap([[DIM[t] for t in r] for r in remap(rows, tones)],
                  keep_isolated=False)


def mask(rows):
    h, w = len(rows), len(rows[0])
    m = [[1] * w for _ in range(h)]
    for y in range(h):
        for x in range(w):
            if rows[y][x] == 0:
                continue
            for dy in (-1, 0, 1):
                for dx in (-1, 0, 1):
                    if 0 <= y + dy < h and 0 <= x + dx < w:
                        m[y + dy][x + dx] = 0
    return m


def pack(lines):
    out = []
    for line in lines:
        for b in range(0, len(line), 8):
            v = 0
            for bit in line[b:b + 8]:
                v = (v << 1) | bit
            out.append(v)
    return out


def emit(f, label, data):
    f.write(f"{label}::\n")
    for i in range(0, len(data), 16):
        f.write("\t.db " + ",".join("0x%02X" % b for b in data[i:i + 16]) + "\n")


def main():
    parsed = {k: art.parse(v, 16, k) for k, v in art.ART.items()}
    h = open(os.path.join(ROOT, "src", "gfx.h"), "w")
    h.write("/* generated by tools/mkgfx.py -- do not edit */\n#ifndef GFX_H\n#define GFX_H\n")
    h.write("#include <stdint.h>\n")
    for i, name in enumerate(TILES):
        h.write(f"#define T_{name} {i}\n")
    for i, name in enumerate(SPRITES):
        h.write(f"#define S_{name} {i}\n")
    h.write("extern const uint8_t tile_gfx[];\nextern const uint8_t tile_dim_gfx[];\n")
    h.write("extern const uint8_t sprite_gfx[];\n")
    h.write("extern const uint8_t font_gfx[];\n")
    h.write("#define TILE_PTR(i) (tile_gfx + ((i) << 5))\n")
    h.write("#define TILE_DIM_PTR(i) (tile_dim_gfx + ((i) << 5))\n")
    h.write("#define SPRITE_PTR(i) (sprite_gfx + ((i) << 6))\n")
    h.write("#endif\n")
    h.close()

    s = open(os.path.join(ROOT, "src", "gfx.s"), "w")
    s.write("; generated by tools/mkgfx.py -- do not edit\n\t.module gfx\n")
    s.write("\t.globl _tile_gfx\n\t.globl _tile_dim_gfx\n\t.globl _sprite_gfx\n"
            "\t.globl _font_gfx\n\t.area _CODE\n")
    tiles, dim = [], []
    for name in TILES:
        tones = art.SPEC_TONES.get(name)
        tiles += pack(bitmap(parsed[name], tones))
        dim += pack(dim_bitmap(parsed[name], tones))
    emit(s, "_tile_gfx", tiles)
    emit(s, "_tile_dim_gfx", dim)
    sprites = []
    for name in SPRITES:
        rows = parsed[name]
        sprites += pack(bitmap(rows)) + pack(mask(rows))
    emit(s, "_sprite_gfx", sprites)
    font = []
    for code in range(32, 96):
        ch = chr(code)
        glyph = art.FONT_SRC.get(ch, art.FONT_SRC[" "])
        rows = glyph.split("|")
        for y in range(8):
            v = 0
            if y < 7:
                for x, c in enumerate(rows[y]):
                    if c == "#":
                        v |= 0x80 >> (x + 1)
            font.append(v)
    emit(s, "_font_gfx", font)
    s.close()
    print(f"gfx: {len(TILES)} tiles (lit and remembered), {len(SPRITES)} sprites, "
          f"{len(tiles) + len(dim) + len(sprites) + len(font)} bytes")


if __name__ == "__main__":
    main()
